name: switcher_button
description: Flutter switch button with minimal design and material animation and highly
  customizable.It can be use as switch button or toggle buttons.
version: 0.0.3
author: mohammad mohammady<mohammad.mohammady.73@gmail.com>
homepage: https://github.com/appiranian/switcher_button.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
